name: A workflow for my Hello World file
on: push # Run on every push to the repo
jobs:
  build: # Id of the job
    name: Hello world action # Used for display
    runs-on: ubuntu-latest # define the machine that runs the job
    steps: # linear sequence of opperation
      - uses: actions/checkout@v1 # allow the access of repository actions (build in)
      - uses: ./action-a # path to my custom action directory
        with: # Define variable used in the runtime env (action's inputs)
          MY_NAME: "Alexis"